name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cgetc/create-github-release-simply@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          name: ${GITHUB_REF#refs/tags/}
          generate-release-notes: true
          draft: true

